[project]
name = "expensetracker"
version = "0.1.0"
description = "Personal expense tracking app"
dependencies = [
    "flet==0.28.3"
]

[build-system]
requires = ["flet"]

[tool.flet.android]
package = "com.fancyzebra.expensetracker"
permissions = [
    "android.permission.INTERNET"
]