name: Build Flet Android APK (Final)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android build tools
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0"

    - name: Install Flet and dependencies
      run: |
        pip install --upgrade pip
        pip install "flet[build-tools]==0.28.3"
        
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Build APK
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        flet build apk --verbose

    - name: Find and prepare APK files
      run: |
        echo "=== Searching for APK files ==="
        
        # Create a staging directory for artifacts
        mkdir -p apk_output
        
        # Find all APK files and copy them to staging
        find . -name "*.apk" -type f | while read apk_file; do
          echo "Found APK: $apk_file"
          cp "$apk_file" apk_output/
          ls -lh "$apk_file"
        done
        
        # List what we found
        echo "=== APK files ready for upload ==="
        ls -la apk_output/
        
        # Create a summary file
        echo "Build completed at: $(date)" > apk_output/build_info.txt
        echo "APK files found:" >> apk_output/build_info.txt
        ls -la apk_output/*.apk >> apk_output/build_info.txt 2>/dev/null || echo "No APK files" >> apk_output/build_info.txt
        
        # Verify we have APK files
        if ls apk_output/*.apk 1> /dev/null 2>&1; then
          echo "✓ APK files ready for upload!"
        else
          echo "❌ No APK files found to upload"
          echo "Full directory structure:"
          find . -type f -name "*.apk" -o -name "*.aab" | head -20
          exit 1
        fi

    - name: Upload APK files
      uses: actions/upload-artifact@v4
      with:
        name: ExpenseTracker-APK
        path: apk_output/
        retention-days: 30
        if-no-files-found: error

    - name: Upload build directory (for debugging)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-directory
        path: |
          build/
        if-no-files-found: ignore
        retention-days: 7